[build]
  command = "composer install && php artisan migrate --force"
  publish = "public"


[[redirects]]
  from = "/*"
  to = "http://backend.example.com/:splat"
  status = 200

[build.environment]
  PHP_VERSION = "8.2"
